// ============================================================
// ROOT BUILD — configuração partilhada por todos os subprojetos
// ============================================================
// Este ficheiro define versões e plugins uma só vez.
// Cada serviço herda estas definições no seu próprio build.gradle.kts.

plugins {
    // O `apply false` significa: declaro o plugin aqui mas não o aplico na raiz.
    // Cada subprojeto escolhe se quer aplicá-lo.
    id("org.springframework.boot") version "4.0.5" apply false
    id("io.spring.dependency-management") version "1.1.7" apply false
    kotlin("jvm") version "2.1.0" apply false  // Kotlin DSL nos build scripts
    // SonarCloud — aplicado na raiz para análise multi-módulo
    id("org.sonarqube") version "5.1.0.4882"
}

// =============================================================================
// SONARCLOUD — configuração do projecto multi-módulo
// =============================================================================
// Variáveis configuradas em GitHub Actions Secrets:
//   SONAR_TOKEN   → Settings → Secrets → Actions → New repository secret
//   SONAR_ORG     → o teu organization slug no SonarCloud (ex: "eliezer-silva")
// =============================================================================
sonar {
    properties {
        property("sonar.projectKey",   System.getenv("SONAR_PROJECT_KEY") ?: "order-platform")
        property("sonar.organization", System.getenv("SONAR_ORG")         ?: "change-me")
        property("sonar.host.url",     "https://sonarcloud.io")
        // Flyway migrations and generated code excluded from analysis
        property("sonar.exclusions",   "**/db/migration/**,**/build/**,**/*Application.java")
        // Point to JaCoCo XML reports for coverage (generated by jacoco plugin)
        property("sonar.coverage.jacoco.xmlReportPaths",
                 "**/build/reports/jacoco/test/jacocoTestReport.xml")
    }
}

// Configuração aplicada a TODOS os subprojetos
subprojects {
    apply(plugin = "io.spring.dependency-management")

    // Repositório onde o Gradle vai buscar as dependências (Maven Central)
    repositories {
        mavenCentral()
    }

    // Versões centralizadas — alterar aqui afeta todos os serviços
    the<io.spring.gradle.dependencymanagement.dsl.DependencyManagementExtension>().apply {
        imports {
            // Spring Boot BOM — define versões de todas as libs Spring
            mavenBom("org.springframework.boot:spring-boot-dependencies:4.0.5")
        }
        dependencies {
            // OpenTelemetry — traces distribuídos
            dependency("io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom:2.26.1")
        }
    }

    // Configuração Java comum a todos os serviços
    plugins.withId("java") {
        extensions.configure<JavaPluginExtension> {
            sourceCompatibility = JavaVersion.VERSION_21
            targetCompatibility = JavaVersion.VERSION_21
        }

        // Encoding UTF-8 para todos os ficheiros Java
        tasks.withType<JavaCompile>().configureEach {
            options.encoding = "UTF-8"
        }

        // Testes sempre com output detalhado
        tasks.withType<Test>().configureEach {
            useJUnitPlatform() // JUnit 5
            testLogging {
                events("passed", "skipped", "failed")
            }
        }

        // JaCoCo — geração de relatórios de cobertura para SonarCloud
        apply(plugin = "jacoco")
        tasks.withType<JacocoReport>().configureEach {
            reports {
                xml.required.set(true)
                html.required.set(true)
            }
        }
        // Gerar relatório JaCoCo após os testes automaticamente
        tasks.named("test") {
            finalizedBy(tasks.named("jacocoTestReport"))
        }
    }
}
