apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.componentLabels" (dict "component" "frontend" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "order-platform.componentSelectorLabels" (dict "component" "frontend" "context" $) | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
