apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.componentLabels" (dict "component" "inventory-service" "context" $) | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: k8s
