apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-db
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.componentLabels" (dict "component" "inventory-service" "context" $) | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.postgresql.credentials.username }}
  DB_PASSWORD: {{ .Values.postgresql.credentials.password }}
