apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.componentLabels" (dict "component" "jaeger" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "order-platform.componentSelectorLabels" (dict "component" "jaeger" "context" $) | nindent 4 }}
  ports:
    - name: ui
      port: 16686
      targetPort: ui
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
