apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.componentLabels" (dict "component" "grafana" "context" $) | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.observability.grafana.admin.username }}
  admin-password: {{ .Values.observability.grafana.admin.password }}
