apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.componentLabels" (dict "component" "grafana" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "order-platform.componentSelectorLabels" (dict "component" "grafana" "context" $) | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
