apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.componentLabels" (dict "component" "keycloak" "context" $) | nindent 4 }}
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgresql:5432/keycloak_db
  KC_HOSTNAME_STRICT: "false"
  KC_HTTP_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
