apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.componentLabels" (dict "component" "keycloak" "context" $) | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.admin.username }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password }}
  KC_DB_USERNAME: {{ .Values.postgresql.credentials.username }}
  KC_DB_PASSWORD: {{ .Values.postgresql.credentials.password }}
