apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.componentLabels" (dict "component" "api-gateway" "context" $) | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: k8s
