apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.componentLabels" (dict "component" "postgresql" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "order-platform.componentSelectorLabels" (dict "component" "postgresql" "context" $) | nindent 4 }}
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
