apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "order-platform.componentLabels" (dict "component" "otel-collector" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "order-platform.componentSelectorLabels" (dict "component" "otel-collector" "context" $) | nindent 4 }}
  ports:
    - name: grpc
      port: 4317
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 4318
      targetPort: http
      protocol: TCP
